import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { join } from "path";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const defaultOutputDir = "dist";
const outputDir = prod
	? defaultOutputDir
	: "./test-vault/.obsidian/plugins/vim-im-select" ?? defaultOutputDir;

// 拷贝必要的目录到指定文件夹

const filesToCopy = ["manifest.json", "versions.json"]; // 指定要复制的文件列表
if (outputDir !== "./") {
	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir);
	}
	filesToCopy.forEach((filePath) => {
		const sourcePath = filePath; // 获取源文件路径
		const destPath = join(outputDir, filePath); // 获取目标文件路径
		fs.copyFileSync(sourcePath, destPath);
	});
}
esbuild
	.build({
		banner: {
			js: banner,
		},
		entryPoints: ["./src/main.ts"],
		bundle: true,
		external: ["obsidian", "electron", ...builtins],
		format: "cjs",
		watch: !prod,
		target: "es2016",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile: join(outputDir, "main.js")
	})
	.catch(() => process.exit(1));
